### ISSUE TITLE
Possibility to offer English support?

### ISSUE THREAD

**Issue by stefanos82** [yourtion/LearningMasteringAlgorithms-C#2]
Hello @yourtion, I hope you can speak English.

I have found many projects on GitHub that are great, but unfortunately they do not offer English support. I'm pretty sure that if you had offered it in the first place, your project would have attracted more traffic than you can imagine and some smart brains that are out there.

Is it possible to gather a group of Chinese friends that can speak English fluently and translate the docs?

It's shame that I can't understand a word. I cannot offer my help in any way and it's sad.

**Comment by yourtion** [comment]
Because the original book and sample code are written by English [Mastering Algorithms with C](http://shop.oreilly.com/product/9781565924536.do), I learn and comment the code in Chinese for the user not know English well. 

So. If you want to see the English version, you can find it here.

http://examples.oreilly.com/9781565924536/

or 

https://github.com/shichao-an/examples_unix
